#!/usr/bin/env zsh

#clean up cruft on the desktop.

echo "${G}Cleaning up image cruft:${R}"

for a in ~/Desktop/*.(png|jpg|jpeg|gif)(.N); do 
	rm -rv $a;
; done

echo "${Y}... Done!"

echo "${G}Cleaning up misc cruft:${R}"

for a in ~/Desktop/*.(zip|dmg|pkg|tar*|pdf|json|xlsx|docx)(.N); do
	rm -ri $a;
; done

echo "${Y}... Done!"