# ~/.tmuxinator/monitor.yml

name: pep-work
root: ~/projects/pep/

windows:
  - pep:
      layout: tiled
      panes:
        - work:
          - cd admin-front-end
          - g st
        - environment:
          - ./refresh.sh
          - pm2 status
        - mongod:
          - mongod
